title: Your Name
description: Undergraduate engineering student — projects & contact
theme: jekyll-theme-minimal   # or: jekyll-theme-slate / jekyll-theme-cayman
logo: /images/avatar.jpg      # optional
